### ISSUE TITLE
Circular dependency for base/tools/cli?

### ISSUE THREAD

**Issue by vrutkovs** [okd-project/okd-payload-pipeline#44]
I think we have a circular deps for main images:
* `base` is build from tools - https://github.com/okd-project/okd-payload-pipeline/blob/main/buildconfigs/05-base.yaml
* `tools` is built from cli - https://github.com/okd-project/okd-payload-pipeline/blob/main/buildconfigs/20-tools.yaml
* `cli` is built from base - https://github.com/okd-project/okd-payload-pipeline/blob/main/buildconfigs/06-cli.yaml

Its not clear where to start when we want to build "real" base image with golang and things

/cc @aleskandro

**Comment by aleskandro** [comment]
Is this actually a circular dependency?

- `base` extends from `tools:centos9`, which is cs9, locally imported in https://github.com/okd-project/okd-payload-pipeline/blob/main/buildconfigs/02-additional-imagestream.yaml#L9
- `cli` is built from `base` <- cs9
- `tools` is built from `cli` <- `base` <- cs9. This is a image meant to be part of the payload with this description `Contains debugging and diagnostic tools for use with an OpenShift cluster.`

**Comment by aleskandro** [comment]
Maybe we can track here what to do for upstreaming the forked dockerfiles for this build config?

**Comment by vrutkovs** [comment]
>base extends from tools:centos9, which is cs9

ooh, indeed, my bad - I though it comes from `tools` buildconfig


>Maybe we can track here what to do for upstreaming the tools's forked dockerfile?

I think it would be confusing to change subject in this issue. Lets create a tracking issue for "upstream more stuff for 4.15" or even per-dockerfile issue
