### ISSUE TITLE
Proposal: Rename repo to okd-payload-pipeline

### ISSUE THREAD

**Issue by LorbusChris** [okd-project/okd-payload-pipeline#8]

**Comment by vrutkovs** [comment]
"payload" is internal name, lets use "rebuild-pipeline"? It also highlights the fact that its not the pipeline we use to build official OKD but a way to build your own. WDYT?

**Comment by LorbusChris** [comment]
I don't really like the `rebuild` in there TBH, and payload seems pretty self-explanatory to me? 
Maybe `okd-payload-tekton-pipeline` or `okd-release-tekton-pipeline`? (Diane noted we should definitely have `okd` in there)
Also cc'ing @dmueller2001 @lmzuccarelli @aleskandro for additional input

**Comment by aleskandro** [comment]
Do we mandatory need to specify it's a tekton pipeline?

Wrt payload vs release, I agree that `release` could be more meaningful for external guys or people approaching the community. 

However, calling it `payload` could bring the community to stay on the same page and call it as we do internally, with a few beneficial side-effects eventually (e.g., when "communicating", support, debugging, raising issues/bugs). I mean, it's "just" the name of a repo, but if we define what a "payload" is, I'd say everybody should use it consistently, and "alias" should be avoided.

**Comment by vrutkovs** [comment]
IMO its fair to add `tekton` here. This implementation uses it, but there might be others - i.e. Jenkins pipeline.
On the other hand `okd-release-tekton-pipeline` may be interpreted as "OKD Tekton operator pipeline". Maybe `build-okd-with-tekton`?

**Comment by aleskandro** [comment]
The renaming has been discussed during today's OKD working group meeting. The proposed name is `okd-payload-pipeline`.

**Comment by vrutkovs** [comment]
Done
